# Use this Blueprint to deploy n8n on Render as a web
# service that uses a Postgres database to store
# workflow data.

services:
  - type: web
    plan: free
    runtime: image
    name: n8n-service
    image:
      url: docker.io/n8nio/n8n:latest

    envVars:
      - key: N8N_ENCRYPTION_KEY
        generateValue: true

      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_DATABASE
        fromDatabase:
          name: n8n-db
          property: database
      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: n8n-db
          property: host
      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: n8n-db
          property: password
      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: n8n-db
          property: user

      # 🔐 Force Basic Auth
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: sayan
      - key: N8N_BASIC_AUTH_PASSWORD
        value: iUseN8nSafely@2025

      # ❌ Explicitly disable User Management
      - key: N8N_USER_MANAGEMENT_DISABLED
        value: "true"

      # 🌐 Optional but good practice
      - key: WEBHOOK_URL
        value: https://n8n-service-r4j9.onrender.com/
      - key: N8N_HOST
        value: n8n-service-r4j9.onrender.com

databases:
  - name: n8n-db
    plan: free
